// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtRpAHAZdX5z8zjGMwhcF8lH1XF62rxm4',
    appId: '1:335777282051:web:a46dcaaad33182442ab636',
    messagingSenderId: '335777282051',
    projectId: 'bwark-81a84',
    authDomain: 'bwark-81a84.firebaseapp.com',
    storageBucket: 'bwark-81a84.appspot.com',
    measurementId: 'G-CD3DJ036SF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBdyolWcN7RYljmj_uKi6YXZVuI8itn5M',
    appId: '1:335777282051:android:6e27833b983036722ab636',
    messagingSenderId: '335777282051',
    projectId: 'bwark-81a84',
    storageBucket: 'bwark-81a84.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAneh5GqF3fzn-ACu1IJ60hk9bggh-6L4',
    appId: '1:335777282051:ios:a4712e8a1c0c7ae62ab636',
    messagingSenderId: '335777282051',
    projectId: 'bwark-81a84',
    storageBucket: 'bwark-81a84.appspot.com',
    iosClientId:
        '335777282051-f1psvm1lvv9pdltl5v1o4e53r7nrh64s.apps.googleusercontent.com',
    iosBundleId: 'com.nautiii.bwark',
  );
}
